name: build
on:
  pull_request:
  push:

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up golang
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.40.1
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run lint
        run: |
          golangci-lint run -v
      - name: Run test
        run: |
          go test -v ./...
